"""Snapshot tests for the runtime (JVM + Go) builtin inspectors.

`add-runtime-inspectors`: `jvm.heap`, `jvm.gc`, `jvm.threads`,
`go.goroutines`, `go.heap`.

These run the **real** `InspectorRunner` against `ReplayTarget` fixtures (see
`tests/inspectors/fixtures/jvm/` + `fixtures/go/`, generated by
`_record_runtime.py`), exercising the full
`preflight → render → collect → parse → findings` path **offline** — zero real
JVM, zero pprof endpoint, zero jstat / jcmd / curl. Non-root.

The JVM inspectors are replayed with the SAME `parameters={"pid": 4242}` the
recorder used so the rendered command (which embeds the pid via the direct
attach path) matches the recorded fixture byte-for-byte. `jvm.gc` is run with
the same frozen clock the recorder used (it declares a sampling_window, so the
runner requires a clock). Every test asserts `replay.misses == []` so any drift
between the rendered command and the recorded fixture fails loud.

Coverage per inspector (D-5 / D-8): a finding-trigger fixture (asserts a finding
fires — proving detection, no no-op), an ok fixture (zero findings), and an
**exception** fixture modelling the target being absent (pid not found / pprof
port unreachable): empty stdout + non-zero exit → `status=exception`. The
exception tests are the spec false-negative guards (runtime-inspector-suite
「unreachable fail-loud 不假阴」): an absent pid / unreachable endpoint MUST
surface as `status=exception`, never a silent `status=ok` with a fabricated
healthy count.

Per design D-7 the collector shell (jstat column-name anchoring D-4, jvm.gc
window differencing D-5, curl fail-loud D-2) is NOT executed under ReplayTarget
— it is locked at the command-string level by the verbatim fixture capture.
`test_*_command_locked` assertions pin those command strings; real behaviour
(cross-JDK column anchoring / window deltas) is verified on the real-machine
Demo Path.
"""

from __future__ import annotations

import json
from datetime import UTC, datetime
from pathlib import Path

import pytest
import structlog

from hostlens.core.config import Settings
from hostlens.inspectors.loader import load_manifest
from hostlens.inspectors.result import InspectorResult
from hostlens.inspectors.runner import InspectorRunner
from hostlens.targets.registry import TargetRegistry
from hostlens.targets.replay import ReplayTarget

_BUILTIN_ROOT = Path(__file__).resolve().parents[2] / "src" / "hostlens" / "inspectors" / "builtin"
_FIXTURE_ROOT = Path(__file__).resolve().parent / "fixtures"

# Must match `_record_runtime.FROZEN_DT` so the sampling_window inspector
# (jvm.gc) renders identically to the recorded fixture.
FROZEN_DT = datetime(2026, 1, 2, 12, 0, 0, tzinfo=UTC)

# Must match `_record_runtime._JVM_PARAMS`: the JVM inspectors are recorded via
# the direct attach path (pid set), so the rendered command embeds this pid.
_JVM_PARAMS = {"pid": 4242}


def _runner() -> InspectorRunner:
    return InspectorRunner(
        TargetRegistry(),
        settings=Settings(),
        logger=structlog.get_logger("test"),
        clock=lambda: FROZEN_DT,
    )


async def _run(
    domain: str,
    inspector: str,
    fixture: str,
    parameters: dict[str, object] | None = None,
) -> tuple[ReplayTarget, InspectorResult]:
    manifest = load_manifest(_BUILTIN_ROOT / domain / f"{inspector}.yaml")
    replay = ReplayTarget("runtime-host", fixture=_FIXTURE_ROOT / domain / fixture)
    result = await _runner().run(manifest, replay, parameters)
    return replay, result


def _fixture_main_cmd(domain: str, fixture: str, needle: str) -> str:
    data = json.loads((_FIXTURE_ROOT / domain / fixture).read_text(encoding="utf-8"))
    return next(c["cmd"] for c in data["commands"] if needle in c["cmd"])


# --------------------------------------------------------------------------- #
# jvm.heap
# --------------------------------------------------------------------------- #


async def test_jvm_heap_critical_detected() -> None:
    replay, result = await _run("jvm", "heap", "heap_critical.json", _JVM_PARAMS)
    assert replay.misses == []
    assert result.status == "ok"
    assert result.output == {"heap_used_pct": 96.0}
    assert len(result.findings) == 1
    assert result.findings[0].severity == "critical"


def test_jvm_heap_command_locked() -> None:
    # D-4 column-name anchoring + D-6.1 non-empty second gate are locked at the
    # command-string level (NOT executed under replay): the recorded command
    # MUST anchor columns by NAME and re-check the derived scalar is non-empty.
    cmd = _fixture_main_cmd("jvm", "heap_critical.json", "jstat -gc")
    assert "pid=4242" in cmd
    assert 'col["EU"]' in cmd
    assert 'col["OU"]' in cmd
    assert '[ -n "$used" ] || exit 1' in cmd


async def test_jvm_heap_ok_no_findings() -> None:
    replay, result = await _run("jvm", "heap", "heap_ok.json", _JVM_PARAMS)
    assert replay.misses == []
    assert result.status == "ok"
    assert result.output == {"heap_used_pct": 50.0}
    assert result.findings == []


async def test_jvm_heap_unreachable_is_exception_not_false_negative() -> None:
    replay, result = await _run("jvm", "heap", "heap_unreachable.json", _JVM_PARAMS)
    assert replay.misses == []
    # pid absent / cross-user attach → fail-loud → exception, NOT a fabricated
    # status=ok with a healthy heap percent.
    assert result.status == "exception"
    assert result.findings == []


# --------------------------------------------------------------------------- #
# jvm.gc
# --------------------------------------------------------------------------- #


async def test_jvm_gc_pressure_detected() -> None:
    replay, result = await _run("jvm", "gc", "gc_pressure.json", _JVM_PARAMS)
    assert replay.misses == []
    assert result.status == "ok"
    assert result.output == {"full_gc_delta": 8, "gc_time_pct": 2.0}
    assert len(result.findings) == 1
    assert result.findings[0].severity == "warning"


def test_jvm_gc_command_locked() -> None:
    # D-5 window differencing is locked at the command-string level: the
    # recorded command MUST double-sample (read → sleep window_seconds → read)
    # and anchor FGC/GCT by column name, collapsing to a frozen scalar.
    cmd = _fixture_main_cmd("jvm", "gc_pressure.json", "jstat -gcutil")
    assert "pid=4242" in cmd
    assert "sleep 5" in cmd  # window_seconds from sampling_window.duration_seconds
    assert "jstat -gcutil" in cmd
    assert '[ -n "$fgc_delta" ] || exit 1' in cmd


async def test_jvm_gc_ok_no_findings() -> None:
    replay, result = await _run("jvm", "gc", "gc_ok.json", _JVM_PARAMS)
    assert replay.misses == []
    assert result.status == "ok"
    assert result.output == {"full_gc_delta": 0, "gc_time_pct": 0.5}
    assert result.findings == []


async def test_jvm_gc_unreachable_is_exception() -> None:
    replay, result = await _run("jvm", "gc", "gc_unreachable.json", _JVM_PARAMS)
    assert replay.misses == []
    assert result.status == "exception"
    assert result.findings == []


# --------------------------------------------------------------------------- #
# jvm.threads
# --------------------------------------------------------------------------- #


async def test_jvm_threads_spike_detected() -> None:
    replay, result = await _run("jvm", "threads", "threads_spike.json", _JVM_PARAMS)
    assert replay.misses == []
    assert result.status == "ok"
    assert result.output == {"thread_total": 700, "blocked_total": 3}
    assert len(result.findings) == 1
    assert result.findings[0].severity == "warning"


def test_jvm_threads_command_locked() -> None:
    # The thread-count parse is locked at the command-string level: the recorded
    # command MUST use jcmd Thread.print and re-check the total is non-empty.
    cmd = _fixture_main_cmd("jvm", "threads_spike.json", "Thread.print")
    assert "pid=4242" in cmd
    assert 'jcmd "$pid" Thread.print' in cmd
    assert '[ -n "$total" ] || exit 1' in cmd


async def test_jvm_threads_ok_no_findings() -> None:
    replay, result = await _run("jvm", "threads", "threads_ok.json", _JVM_PARAMS)
    assert replay.misses == []
    assert result.status == "ok"
    assert result.output == {"thread_total": 100, "blocked_total": 0}
    assert result.findings == []


async def test_jvm_threads_unreachable_is_exception() -> None:
    replay, result = await _run("jvm", "threads", "threads_unreachable.json", _JVM_PARAMS)
    assert replay.misses == []
    assert result.status == "exception"
    assert result.findings == []


# --------------------------------------------------------------------------- #
# go.goroutines
# --------------------------------------------------------------------------- #


async def test_go_goroutines_leak_detected() -> None:
    replay, result = await _run("go", "goroutines", "goroutines_leak.json")
    assert replay.misses == []
    assert result.status == "ok"
    assert result.output == {"goroutines": 50000}
    assert len(result.findings) == 1
    assert result.findings[0].severity == "warning"


def test_go_goroutines_command_locked() -> None:
    # D-2 curl fail-loud is locked at the command-string level: the recorded
    # command MUST `|| exit 1` on curl (not `|| true`) and re-check the parsed
    # total is non-empty.
    cmd = _fixture_main_cmd("go", "goroutines_leak.json", "/debug/pprof/goroutine")
    assert "/debug/pprof/goroutine?debug=1" in cmd
    assert "|| exit 1" in cmd
    assert '[ -n "$total" ] || exit 1' in cmd


async def test_go_goroutines_ok_no_findings() -> None:
    replay, result = await _run("go", "goroutines", "goroutines_ok.json")
    assert replay.misses == []
    assert result.status == "ok"
    assert result.output == {"goroutines": 100}
    assert result.findings == []


async def test_go_goroutines_unreachable_is_exception_not_false_negative() -> None:
    replay, result = await _run("go", "goroutines", "goroutines_unreachable.json")
    assert replay.misses == []
    # pprof port down → curl fail-loud → exception, NOT status=ok goroutines=0.
    assert result.status == "exception"
    assert result.findings == []


# --------------------------------------------------------------------------- #
# go.heap
# --------------------------------------------------------------------------- #


async def test_go_heap_pressure_detected() -> None:
    replay, result = await _run("go", "heap", "heap_pressure.json")
    assert replay.misses == []
    assert result.status == "ok"
    assert result.output == {"heap_inuse_bytes": 2000000000, "heap_alloc_bytes": 1500000000}
    assert len(result.findings) == 1
    assert result.findings[0].severity == "warning"


def test_go_heap_command_locked() -> None:
    cmd = _fixture_main_cmd("go", "heap_pressure.json", "/debug/pprof/heap")
    assert "/debug/pprof/heap?debug=1" in cmd
    assert "|| exit 1" in cmd
    assert '[ -n "$inuse" ] || exit 1' in cmd


async def test_go_heap_ok_no_findings() -> None:
    replay, result = await _run("go", "heap", "heap_ok.json")
    assert replay.misses == []
    assert result.status == "ok"
    assert result.output == {"heap_inuse_bytes": 100000000, "heap_alloc_bytes": 80000000}
    assert result.findings == []


async def test_go_heap_unreachable_is_exception() -> None:
    replay, result = await _run("go", "heap", "heap_unreachable.json")
    assert replay.misses == []
    assert result.status == "exception"
    assert result.findings == []


# --------------------------------------------------------------------------- #
# Suite-level false-negative sweep (task 3.3)
# --------------------------------------------------------------------------- #


@pytest.mark.parametrize(
    ("domain", "inspector", "fixture", "parameters"),
    [
        ("jvm", "heap", "heap_unreachable.json", _JVM_PARAMS),
        ("jvm", "gc", "gc_unreachable.json", _JVM_PARAMS),
        ("jvm", "threads", "threads_unreachable.json", _JVM_PARAMS),
        ("go", "goroutines", "goroutines_unreachable.json", None),
        ("go", "heap", "heap_unreachable.json", None),
    ],
)
async def test_runtime_absent_target_never_silent_ok(
    domain: str,
    inspector: str,
    fixture: str,
    parameters: dict[str, object] | None,
) -> None:
    # spec runtime-inspector-suite core false-negative guard, swept across all
    # 5: an absent pid (JVM) / unreachable pprof endpoint (Go) MUST be
    # status=exception, never status=ok with a fabricated healthy count.
    _, result = await _run(domain, inspector, fixture, parameters)
    assert result.status == "exception", f"{domain}.{inspector} swallowed an absent target as ok"
    assert result.findings == []
